# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peckboard.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpeckboard.proto\"\x1d\n\x08LedState\x12\x11\n\tled_state\x18\x01 \x01(\t\"\x0b\n\tLedParams\"F\n\x08KeyState\x12\x11\n\tpeck_left\x18\x01 \x01(\x08\x12\x13\n\x0bpeck_center\x18\x02 \x01(\x08\x12\x12\n\npeck_right\x18\x03 \x01(\x08\"\x0b\n\tKeyParamsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peckboard_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LEDSTATE._serialized_start=19
  _LEDSTATE._serialized_end=48
  _LEDPARAMS._serialized_start=50
  _LEDPARAMS._serialized_end=61
  _KEYSTATE._serialized_start=63
  _KEYSTATE._serialized_end=133
  _KEYPARAMS._serialized_start=135
  _KEYPARAMS._serialized_end=146
# @@protoc_insertion_point(module_scope)
