# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decide.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='decide.proto',
  package='decide',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x64\x65\x63ide.proto\x12\x06\x64\x65\x63ide\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n\x0bStateChange\x12#\n\x05state\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\";\n\x0f\x43omponentParams\x12(\n\nparameters\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"\x1c\n\x06\x43onfig\x12\x12\n\nidentifier\x18\x01 \x01(\t\"p\n\x05Reply\x12$\n\x02ok\x18\x02 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x12\x0f\n\x05\x65rror\x18\x03 \x01(\tH\x00\x12&\n\x06params\x18\x13 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x42\x08\n\x06result\"T\n\x03Pub\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12#\n\x05state\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any2\xcc\x02\n\rDecideControl\x12\x31\n\x0b\x43hangeState\x12\x13.decide.StateChange\x1a\r.decide.Reply\x12\x33\n\nResetState\x12\x16.google.protobuf.Empty\x1a\r.decide.Reply\x12,\n\x0bRequestLock\x12\x0e.decide.Config\x1a\r.decide.Reply\x12\x34\n\x0bReleaseLock\x12\x16.google.protobuf.Empty\x1a\r.decide.Reply\x12\x37\n\rSetParameters\x12\x17.decide.ComponentParams\x1a\r.decide.Reply\x12\x36\n\rGetParameters\x12\x16.google.protobuf.Empty\x1a\r.decide.Replyb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_STATECHANGE = _descriptor.Descriptor(
  name='StateChange',
  full_name='decide.StateChange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='decide.StateChange.state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=163,
)


_COMPONENTPARAMS = _descriptor.Descriptor(
  name='ComponentParams',
  full_name='decide.ComponentParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='parameters', full_name='decide.ComponentParams.parameters', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=224,
)


_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='decide.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='decide.Config.identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=254,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='decide.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='decide.Reply.ok', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='decide.Reply.error', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='decide.Reply.params', index=2,
      number=19, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='result', full_name='decide.Reply.result',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=256,
  serialized_end=368,
)


_PUB = _descriptor.Descriptor(
  name='Pub',
  full_name='decide.Pub',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='decide.Pub.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='decide.Pub.state', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=454,
)

_STATECHANGE.fields_by_name['state'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_COMPONENTPARAMS.fields_by_name['parameters'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_REPLY.fields_by_name['ok'].message_type = google_dot_protobuf_dot_empty__pb2._EMPTY
_REPLY.fields_by_name['params'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_REPLY.oneofs_by_name['result'].fields.append(
  _REPLY.fields_by_name['ok'])
_REPLY.fields_by_name['ok'].containing_oneof = _REPLY.oneofs_by_name['result']
_REPLY.oneofs_by_name['result'].fields.append(
  _REPLY.fields_by_name['error'])
_REPLY.fields_by_name['error'].containing_oneof = _REPLY.oneofs_by_name['result']
_REPLY.oneofs_by_name['result'].fields.append(
  _REPLY.fields_by_name['params'])
_REPLY.fields_by_name['params'].containing_oneof = _REPLY.oneofs_by_name['result']
_PUB.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_PUB.fields_by_name['state'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['StateChange'] = _STATECHANGE
DESCRIPTOR.message_types_by_name['ComponentParams'] = _COMPONENTPARAMS
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
DESCRIPTOR.message_types_by_name['Pub'] = _PUB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StateChange = _reflection.GeneratedProtocolMessageType('StateChange', (_message.Message,), {
  'DESCRIPTOR' : _STATECHANGE,
  '__module__' : 'decide_pb2'
  # @@protoc_insertion_point(class_scope:decide.StateChange)
  })
_sym_db.RegisterMessage(StateChange)

ComponentParams = _reflection.GeneratedProtocolMessageType('ComponentParams', (_message.Message,), {
  'DESCRIPTOR' : _COMPONENTPARAMS,
  '__module__' : 'decide_pb2'
  # @@protoc_insertion_point(class_scope:decide.ComponentParams)
  })
_sym_db.RegisterMessage(ComponentParams)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'decide_pb2'
  # @@protoc_insertion_point(class_scope:decide.Config)
  })
_sym_db.RegisterMessage(Config)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'decide_pb2'
  # @@protoc_insertion_point(class_scope:decide.Reply)
  })
_sym_db.RegisterMessage(Reply)

Pub = _reflection.GeneratedProtocolMessageType('Pub', (_message.Message,), {
  'DESCRIPTOR' : _PUB,
  '__module__' : 'decide_pb2'
  # @@protoc_insertion_point(class_scope:decide.Pub)
  })
_sym_db.RegisterMessage(Pub)



_DECIDECONTROL = _descriptor.ServiceDescriptor(
  name='DecideControl',
  full_name='decide.DecideControl',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=457,
  serialized_end=789,
  methods=[
  _descriptor.MethodDescriptor(
    name='ChangeState',
    full_name='decide.DecideControl.ChangeState',
    index=0,
    containing_service=None,
    input_type=_STATECHANGE,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ResetState',
    full_name='decide.DecideControl.ResetState',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RequestLock',
    full_name='decide.DecideControl.RequestLock',
    index=2,
    containing_service=None,
    input_type=_CONFIG,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReleaseLock',
    full_name='decide.DecideControl.ReleaseLock',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetParameters',
    full_name='decide.DecideControl.SetParameters',
    index=4,
    containing_service=None,
    input_type=_COMPONENTPARAMS,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetParameters',
    full_name='decide.DecideControl.GetParameters',
    index=5,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DECIDECONTROL)

DESCRIPTOR.services_by_name['DecideControl'] = _DECIDECONTROL

# @@protoc_insertion_point(module_scope)
