# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: house_light.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='house_light.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11house_light.proto\"P\n\x07HlState\x12\x0e\n\x06manual\x18\x01 \x01(\x08\x12\x10\n\x08\x65phemera\x18\x02 \x01(\x08\x12\x12\n\nbrightness\x18\x03 \x01(\x05\x12\x0f\n\x07\x64\x61ytime\x18\x04 \x01(\x08\"\"\n\x08HlParams\x12\x16\n\x0e\x63lock_interval\x18\x01 \x01(\x03\x62\x06proto3'
)




_HLSTATE = _descriptor.Descriptor(
  name='HlState',
  full_name='HlState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='manual', full_name='HlState.manual', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ephemera', full_name='HlState.ephemera', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='brightness', full_name='HlState.brightness', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='daytime', full_name='HlState.daytime', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=101,
)


_HLPARAMS = _descriptor.Descriptor(
  name='HlParams',
  full_name='HlParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clock_interval', full_name='HlParams.clock_interval', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=137,
)

DESCRIPTOR.message_types_by_name['HlState'] = _HLSTATE
DESCRIPTOR.message_types_by_name['HlParams'] = _HLPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HlState = _reflection.GeneratedProtocolMessageType('HlState', (_message.Message,), {
  'DESCRIPTOR' : _HLSTATE,
  '__module__' : 'house_light_pb2'
  # @@protoc_insertion_point(class_scope:HlState)
  })
_sym_db.RegisterMessage(HlState)

HlParams = _reflection.GeneratedProtocolMessageType('HlParams', (_message.Message,), {
  'DESCRIPTOR' : _HLPARAMS,
  '__module__' : 'house_light_pb2'
  # @@protoc_insertion_point(class_scope:HlParams)
  })
_sym_db.RegisterMessage(HlParams)


# @@protoc_insertion_point(module_scope)
