# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peckboard.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='peckboard.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fpeckboard.proto\"\x1d\n\x08LedState\x12\x11\n\tled_state\x18\x01 \x01(\t\"\x0b\n\tLedParams\"F\n\x08KeyState\x12\x11\n\tpeck_left\x18\x01 \x01(\x08\x12\x13\n\x0bpeck_center\x18\x02 \x01(\x08\x12\x12\n\npeck_right\x18\x03 \x01(\x08\"\x0b\n\tKeyParamsb\x06proto3'
)




_LEDSTATE = _descriptor.Descriptor(
  name='LedState',
  full_name='LedState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='led_state', full_name='LedState.led_state', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=48,
)


_LEDPARAMS = _descriptor.Descriptor(
  name='LedParams',
  full_name='LedParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=61,
)


_KEYSTATE = _descriptor.Descriptor(
  name='KeyState',
  full_name='KeyState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='peck_left', full_name='KeyState.peck_left', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='peck_center', full_name='KeyState.peck_center', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='peck_right', full_name='KeyState.peck_right', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=133,
)


_KEYPARAMS = _descriptor.Descriptor(
  name='KeyParams',
  full_name='KeyParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['LedState'] = _LEDSTATE
DESCRIPTOR.message_types_by_name['LedParams'] = _LEDPARAMS
DESCRIPTOR.message_types_by_name['KeyState'] = _KEYSTATE
DESCRIPTOR.message_types_by_name['KeyParams'] = _KEYPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LedState = _reflection.GeneratedProtocolMessageType('LedState', (_message.Message,), {
  'DESCRIPTOR' : _LEDSTATE,
  '__module__' : 'peckboard_pb2'
  # @@protoc_insertion_point(class_scope:LedState)
  })
_sym_db.RegisterMessage(LedState)

LedParams = _reflection.GeneratedProtocolMessageType('LedParams', (_message.Message,), {
  'DESCRIPTOR' : _LEDPARAMS,
  '__module__' : 'peckboard_pb2'
  # @@protoc_insertion_point(class_scope:LedParams)
  })
_sym_db.RegisterMessage(LedParams)

KeyState = _reflection.GeneratedProtocolMessageType('KeyState', (_message.Message,), {
  'DESCRIPTOR' : _KEYSTATE,
  '__module__' : 'peckboard_pb2'
  # @@protoc_insertion_point(class_scope:KeyState)
  })
_sym_db.RegisterMessage(KeyState)

KeyParams = _reflection.GeneratedProtocolMessageType('KeyParams', (_message.Message,), {
  'DESCRIPTOR' : _KEYPARAMS,
  '__module__' : 'peckboard_pb2'
  # @@protoc_insertion_point(class_scope:KeyParams)
  })
_sym_db.RegisterMessage(KeyParams)


# @@protoc_insertion_point(module_scope)
