# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sound_alsa.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sound_alsa.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10sound_alsa.proto\"\x85\x01\n\x07SaState\x12\x10\n\x08\x61udio_id\x18\x01 \x01(\t\x12#\n\x08playback\x18\x02 \x01(\x0e\x32\x11.SaState.PlayBack\x12\x13\n\x0b\x66rame_count\x18\x03 \x01(\r\".\n\x08PlayBack\x12\x0b\n\x07STOPPED\x10\x00\x12\x0b\n\x07PLAYING\x10\x01\x12\x08\n\x04NEXT\x10\x02\"G\n\x08SaParams\x12\x11\n\taudio_dir\x18\x01 \x01(\t\x12\x13\n\x0b\x61udio_count\x18\x02 \x01(\r\x12\x13\n\x0bsample_rate\x18\x03 \x01(\rb\x06proto3'
)



_SASTATE_PLAYBACK = _descriptor.EnumDescriptor(
  name='PlayBack',
  full_name='SaState.PlayBack',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOPPED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PLAYING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NEXT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=108,
  serialized_end=154,
)
_sym_db.RegisterEnumDescriptor(_SASTATE_PLAYBACK)


_SASTATE = _descriptor.Descriptor(
  name='SaState',
  full_name='SaState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio_id', full_name='SaState.audio_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='playback', full_name='SaState.playback', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_count', full_name='SaState.frame_count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SASTATE_PLAYBACK,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=154,
)


_SAPARAMS = _descriptor.Descriptor(
  name='SaParams',
  full_name='SaParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio_dir', full_name='SaParams.audio_dir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='audio_count', full_name='SaParams.audio_count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_rate', full_name='SaParams.sample_rate', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=227,
)

_SASTATE.fields_by_name['playback'].enum_type = _SASTATE_PLAYBACK
_SASTATE_PLAYBACK.containing_type = _SASTATE
DESCRIPTOR.message_types_by_name['SaState'] = _SASTATE
DESCRIPTOR.message_types_by_name['SaParams'] = _SAPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SaState = _reflection.GeneratedProtocolMessageType('SaState', (_message.Message,), {
  'DESCRIPTOR' : _SASTATE,
  '__module__' : 'sound_alsa_pb2'
  # @@protoc_insertion_point(class_scope:SaState)
  })
_sym_db.RegisterMessage(SaState)

SaParams = _reflection.GeneratedProtocolMessageType('SaParams', (_message.Message,), {
  'DESCRIPTOR' : _SAPARAMS,
  '__module__' : 'sound_alsa_pb2'
  # @@protoc_insertion_point(class_scope:SaParams)
  })
_sym_db.RegisterMessage(SaParams)


# @@protoc_insertion_point(module_scope)
