# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sound_alsa.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10sound_alsa.proto\x1a\x1egoogle/protobuf/duration.proto\"\x98\x01\n\x05State\x12\x10\n\x08\x61udio_id\x18\x01 \x01(\t\x12!\n\x08playback\x18\x02 \x01(\x0e\x32\x0f.State.PlayBack\x12*\n\x07\x65lapsed\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\".\n\x08PlayBack\x12\x0b\n\x07STOPPED\x10\x00\x12\x0b\n\x07PLAYING\x10\x01\x12\x08\n\x04NEXT\x10\x02\"0\n\x06Params\x12\x11\n\taudio_dir\x18\x01 \x01(\t\x12\x13\n\x0b\x61udio_count\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sound_alsa_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STATE']._serialized_start=53
  _globals['_STATE']._serialized_end=205
  _globals['_STATE_PLAYBACK']._serialized_start=159
  _globals['_STATE_PLAYBACK']._serialized_end=205
  _globals['_PARAMS']._serialized_start=207
  _globals['_PARAMS']._serialized_end=255
# @@protoc_insertion_point(module_scope)
