# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stepper_motor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13stepper_motor.proto\"9\n\x08sm_State\x12\x0e\n\x06switch\x18\x01 \x01(\x08\x12\n\n\x02on\x18\x02 \x01(\x08\x12\x11\n\tdirection\x18\x03 \x01(\x08\"\x1c\n\tsm_Params\x12\x0f\n\x07timeout\x18\x01 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stepper_motor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SM_STATE']._serialized_start=23
  _globals['_SM_STATE']._serialized_end=80
  _globals['_SM_PARAMS']._serialized_start=82
  _globals['_SM_PARAMS']._serialized_end=110
# @@protoc_insertion_point(module_scope)
