# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: sound_alsa.proto
# plugin: python-betterproto
from dataclasses import dataclass
from datetime import timedelta

import betterproto


class SaStatePlayBack(betterproto.Enum):
    STOPPED = 0
    PLAYING = 1
    NEXT = 2


@dataclass
class SaState(betterproto.Message):
    audio_id: str = betterproto.string_field(1)
    playback: "SaStatePlayBack" = betterproto.enum_field(2)
    elapsed: timedelta = betterproto.message_field(3)


@dataclass
class SaParams(betterproto.Message):
    audio_dir: str = betterproto.string_field(1)
    audio_count: int = betterproto.uint32_field(2)
