# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: peckboard.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class LedState(betterproto.Message):
    led_state: str = betterproto.string_field(1)


@dataclass
class LedParams(betterproto.Message):
    pass


@dataclass
class KeyState(betterproto.Message):
    peck_left: bool = betterproto.bool_field(1)
    peck_center: bool = betterproto.bool_field(2)
    peck_right: bool = betterproto.bool_field(3)


@dataclass
class KeyParams(betterproto.Message):
    pass
