# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: stepper_motor.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SmState(betterproto.Message):
    running: bool = betterproto.bool_field(2)
    direction: bool = betterproto.bool_field(3)


@dataclass
class SmParams(betterproto.Message):
    timeout: int = betterproto.uint64_field(1)
